#!/bin/bash

runTest() {
    for test in Test_*
    do
	pushd "${test}"
	echo Priming ${test} with $1
	./run ../"$1"
	echo Timing ${test} with $1
	time ./run ../"$1"
	popd
    done
}

if [ $# -gt 0 ]; then
    runTest "$1"
else
    for bench in Samples/*.txt; do
	runTest "${bench}"
    done
fi

